name: Docker Build y Push

on:
  push:
    branches: [ "main" ] # Ejecutar al hacer push en main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir y subir imagen
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: usuario/mi-app:latest
